name: Dev Build

on:
  push:
  #pull_request:
    branches:
      - dev
  
jobs:
  prepare: 
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME:
      AWS_REGION:
    steps:

    - name: Hello-world
      run: echo Hello-World.
    
    - name: Get branch name
      id: branch
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF} | tr / -)"
        else
          echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | tr / -)"
        fi
    
    outputs:
      BRANCH_NAME: ${{ steps.branch.outputs.BRANCH_NAME }}

  build:
    runs-on: ubuntu-latest
    needs: [ prepare ]
    env:
      BRANCH_NAME: ${{needs.prepare.outputs.BRANCH_NAME}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::478111762044:role/aws-traning-saul-eks-dev-role/my-github-actions-role
        aws-region: us-east-1