name: Dev Build

on:
  push:
  #pull_request:
    branches:
      - dev
  
jobs:
  prepare: 
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME:
      AWS_REGION:
    steps:

    - name: Hello-world
      run: echo Hello-World.
    
    - name: Get branch name
      id: branch
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF} | tr / -)"
        else
          echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | tr / -)"
        fi
    
    outputs:
      BRANCH_NAME: ${{ steps.branch.outputs.BRANCH_NAME }}

  build:
    runs-on: ubuntu-latest
    needs: [ prepare ]
    env:
      BRANCH_NAME: ${{needs.prepare.outputs.BRANCH_NAME}}
    steps:
    - uses: actions/checkout@v1

    - name: Docker login to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: $(aws ecr get-login-password --region ${{ secrets.AWS_REGION }})

    - name: Build docker image
      run: |
        docker build  --network=host \
                      --build-arg=AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
                      --build-arg=AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
                      --build-arg=AWS_REGION="${{ secrets.AWS_REGION }}" \
                      -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.CLUSTER_NAME }}-${{env.BRANCH_NAME}}/${{ secrets.MODULE_NAME }}:${{env.BRANCH_NAME}}-${{ github.sha }} \
    
    - name: Push docker image to AWS ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.CLUSTER_NAME }}-${{env.BRANCH_NAME}}/${{ secrets.MODULE_NAME }}:${{env.BRANCH_NAME}}-${{ github.sha }}
